src/models/exercise.py
from typing import Self, Optional

from . import db
from .exercise_enums import ExerciseType, BodyPart, Equipment, Level


class Exercise:
    def __init__(
        self,
        title: str,
        description: str,
        type: ExerciseType,
        body_part: BodyPart,
        equipment: Equipment,
        level: Level,
        *args,
        **kwargs,
    ) -> None:
        self.id = kwargs.get("id")
        self.title = title
        self.description = description
        self.type = type
        self.body_part = body_part
        self.equipment = equipment
        self.level = level

    @classmethod
    def get(cls, id: int):
        exercises = db.fetch_query(
            'SELECT * FROM public."Exercise" WHERE id = %s ', (id,)
        )

        if not exercises:
            return None

        user = exercises[0]

        return cls(**user)

    @classmethod
    def get_all(cls):
        exercises = db.fetch_query('SELECT * FROM public."Exercise";')
        return [cls(**exercise) for exercise in exercises]

    @classmethod
    def insert(cls, exercise: Self) -> None:
        if exercise.title is None:
            raise ValueError("Cannot insert exercise with title set to NULL.")
        if exercise.type is None:
            raise ValueError("Cannot insert exercise with type set to NULL.")
        if exercise.body_part is None:
            raise ValueError("Cannot insert exercise with body_part set to NULL.")
        if exercise.level is None:
            raise ValueError("Cannot insert exercise with level set to NULL.")

        db.execute_query(
            'INSERT INTO public."Exercise" ("title", "description", "type", "body_part", "equipment", "level") VALUES (%s, %s, %s, %s, %s, %s)',
            (
                exercise.title,
                exercise.description,
                exercise.type,
                exercise.body_part,
                exercise.equipment,
                exercise.level,
            ),
        )

    @classmethod
    def search(
        cls,
        title: Optional[str] = None,
        type: Optional[ExerciseType] = None,
        body_part: Optional[BodyPart] = None,
        equipment: Optional[Equipment] = None,
        level: Optional[Level] = None,
    ):
        values = (title, type, body_part, equipment, level)
        if all(not bool(value) for value in values):
            return Exercise.get_all()

        query = 'SELECT * FROM public."Exercise" WHERE '
        conditions = []
        variables = []

        if title:
            conditions.append("title ILIKE %s")
            variables.append("%" + title + "%")

        if type:
            conditions.append("type=%s")
            variables.append(type)

        if body_part:
            conditions.append("body_part=%s")
            variables.append(body_part)

        if equipment:
            conditions.append("equipment=%s")
            variables.append(equipment)

        if level:
            conditions.append("level=%s")
            variables.append(level)

        query += " AND ".join(conditions) + ";"

        exercises = db.fetch_query(query, variables)
        return [cls(**exercise) for exercise in exercises]

    @classmethod
    def delete(cls, id: int) -> None:
        db.execute_query('DELETE FROM public."Exercise" WHERE id = %s;', (id,))

    def __str__(self):
        return f"Exercise(id={self.id}, title={self.title}, type={self.type}, body_part={self.body_part}, level={self.level}, equipment={self.equipment})"

src/models/workout_request.py
from typing import Self

from . import db
import src.models.client as client
import src.models.trainer as trainer
from datetime import date, datetime
from .trainer_request import Status


class WorkoutRequest:
    def __init__(
        self,
        client: int,
        timestamp: date,
        trainer: int,
        description: str,
        status: str = Status.Pending,
        *args,
        **kwargs,
    ) -> None:
        self.id = kwargs.get("id")
        self.client = client
        self.timestamp = timestamp
        self.trainer = trainer
        self.description = description
        self.status = status

    @classmethod
    def get_requests_by_trainer(cls, trainer: int):
        workout_requests = db.fetch_query(
            'SELECT * FROM public."WorkoutRequest" WHERE trainer = %s',
            (trainer,),
        )

        if not workout_requests:
            return None

        return [cls(**r) for r in workout_requests]

    @classmethod
    def get_requests_by_client(cls, client: int):
        workout_requests = db.fetch_query(
            'SELECT * FROM public."WorkoutRequest" WHERE client = %s',
            (client,),
        )

        if not workout_requests:
            return None

        return [cls(**r) for r in workout_requests]

    @classmethod
    def insert(cls, workout_request: Self) -> None:
        if workout_request.client is None:
            raise ValueError("Cannot insert workout_request with client set to NULL.")

        if workout_request.trainer is None:
            raise ValueError("Cannot insert workout_request with trainer set to NULL.")

        if workout_request.timestamp is None:
            raise ValueError(
                "Cannot insert workout_request with timestamp set to NULL."
            )
        if not workout_request.description:
            raise ValueError(
                "Cannot insert workout_request with description set to NULL."
            )

        t = trainer.Trainer.get(workout_request.trainer)

        if t is None:
            raise ValueError("Cannot assign workout plan to non existing trainer.")

        c = client.Client.get(workout_request.client)

        if c is None:
            raise ValueError("Cannot assign workout plan to non existing client.")

        db.execute_query(
            'INSERT INTO public."WorkoutRequest" ("client", "timestamp", "trainer", "description", "status") VALUES (%s, %s, %s, %s, %s)',
            (
                workout_request.client,
                workout_request.timestamp,
                workout_request.trainer,
                workout_request.description,
                workout_request.status,
            ),
        )

    @classmethod
    def delete(cls, id: int) -> None:
        db.execute_query(
            'DELETE FROM public."WorkoutRequest" WHERE id = %s',
            (id,),
        )

    def update_status(self, new_status: Status):
        if self.status == new_status:
            return
        db.execute_query(
            'UPDATE public."WorkoutRequest" SET status = %s WHERE id = %s;',
            (new_status, self.id),
        )

    @classmethod
    def get(cls, plan_id: int):
        requests = db.fetch_query(
            'SELECT * FROM public."WorkoutRequest" WHERE id = %s ',
            (plan_id,),
        )
        if not requests:
            return None

        return cls(**requests[0])

    def get_trainer(self):
        return trainer.Trainer.get(self.trainer)

    def get_client(self):
        return client.Client.get(self.client)

    def __str__(self):

        return f"WorkoutRequest(id={self.id}, client={self.client}, timestamp={self.timestamp}, trainer={self.trainer}, description={self.description}, status={self.status})"

src/blueprints/base/routes.py
from datetime import datetime
from flask import (
    Blueprint,
    request,
    redirect,
    url_for,
    render_template,
    flash,
    Response,
)
from flask_login import login_required, current_user, logout_user, login_user
from flask_htmx import HTMX

from src.models.client import Client
from src.models.base_user import UserRole
from src.models.user import User
from src.models.exercise import Exercise
from src.models.food import Food
from src.models.exercise_enums import ExerciseType, Level, Equipment, BodyPart
from src.models.trainer_request import TrainerRequest
from src.models.trainer import Trainer

base_bp = Blueprint("base", __name__)
htmx = HTMX(base_bp)


@base_bp.route("/client-request", methods=["POST"])
@login_required
def client_request():
    if current_user.role != UserRole.User:
        return Response("Bad Request", 400)

    c = Client(
        email=current_user.email,
        first_name=current_user.first_name,
        last_name=current_user.last_name,
        password=current_user._password,
    )
    Client.insert(c)
    User.delete(current_user.id)
    logout_user()
    c = Client.get_by_email(c.email)
    login_user(c)
    return redirect(url_for("client.dashboard"))


@base_bp.route("/trainer-request", methods=["POST", "GET"])
@login_required
def trainer_request():
    if current_user.role != UserRole.User:
        return Response("Bad Request", 400)

    if request.method == "POST" and htmx:

        description = request.form.get("description")
        linked_in = request.form.get("linkedin_url")

        TrainerRequest.insert(
            TrainerRequest(current_user.id, datetime.now(), description, linked_in)
        )

        return render_template(
            "trainer/trainer_requests.html",
            trainer_requests=TrainerRequest.get_by_user(current_user.id),
        )

    return render_template(
        "trainer/trainer_onboarding.html",
        trainer_requests=TrainerRequest.get_by_user(current_user.id),
    )


@base_bp.route("/")
def home():
    if current_user.is_authenticated:
        if current_user.role == UserRole.User:
            return redirect(url_for("base.onboarding"))
        if current_user.role == UserRole.Admin:
            return redirect(url_for("admin.dashboard"))
        if current_user.role == UserRole.Client:
            return redirect(url_for("client.dashboard"))
        if current_user.role == UserRole.Trainer:
            return redirect(url_for("trainer.profile"))
    return render_template("home.html")


@base_bp.route("/onboarding")
@login_required
def onboarding():
    if current_user.role != UserRole.User:
        return redirect(url_for("base.home"))

    return render_template("onboarding.html")


@base_bp.route("/exercises", methods=["GET"])
@login_required
def exercises():
    if current_user.role == UserRole.User:
        return redirect(url_for("base.onboarding"))

    return render_template(
        "exercises.html",
        levels=Level,
        exercise_types=ExerciseType,
        body_parts=BodyPart,
        equipment_types=Equipment,
    )


@base_bp.route("/exercise-search")
@login_required
def exercise_search():
    if not htmx:
        return Response("Bad Request", status=201)

    if current_user.role == UserRole.User:
        return redirect(url_for("base.onboarding"))

    title = request.args.get("title")
    exercise_type = request.args.get("type")
    body_part = request.args.get("body_part")
    equipment = request.args.get("equipment")
    level = request.args.get("level")

    exercises = Exercise.search(title, exercise_type, body_part, equipment, level)

    return render_template("partials/exercise_table.html", exercises=exercises)


@base_bp.route("/exercises/<int:exercise_id>")
@login_required
def show_exercise(exercise_id):

    if not htmx:
        return Response("Bad Request", status=201)

    if current_user.role == UserRole.User:
        return redirect(url_for("base.onboarding"))

    exercise = Exercise.get(exercise_id)

    if exercise is None:
        return Response("Bad Request", status=201)

    return render_template("partials/show_exercise.html", exercise=exercise)


@base_bp.route("/nutrition")
@login_required
def nutrition():
    if current_user.role == UserRole.User:
        return redirect(url_for("base.onboarding"))
    return render_template("nutrition.html")


@base_bp.route("/nutrition-search")
@login_required
def nutrition_search():
    if not htmx:
        return Response("Bad Request", status=201)

    if current_user.role == UserRole.User:
        return redirect(url_for("base.onboarding"))

    name = request.args.get("food")
    food = Food.search(name=name)

    return render_template("partials/nutrition_table.html", food=food)


@base_bp.route("/community")
@login_required
def community():
    if current_user.role == UserRole.User:
        return redirect(url_for("base.onboarding"))

    return render_template("community.html", trainers=Trainer.get_all())


@base_bp.route("/settings")
@login_required
def settings():
    if current_user.role == UserRole.User:
        return redirect(url_for("base.onboarding"))
    return render_template("settings.html")

src/templates/partials/class_enroll.html
{% from 'components/buttons.html' import primary_button %}

<h1 class="text-center
    {% if message.error %}
        text-red-500
    {% else %}
        text-green-500
    {% endif %}
    ">
    {{message.message}}
</h1>

{% if htmx and not message.error %}
        {% set button_id = "button-c-" + training_class.id|string %}
        {{ primary_button(
            text='Enrolled!',
            classes='w-full py-2 px-4 text-white rounded-lg bg-gray-300 cursor-not-allowed opacity-50',
            attrs={
                "disabled": "true",
                "hx-swap-oob": "true",
                "id": button_id
            }
        ) }}
{% endif %}

src/templates/partials/exercise_table.html
{% if exercises %}
<table class="w-full max-w-4xl mx-auto border-collapse bg-white shadow-md rounded-lg overflow-hidden">
    <thead class="bg-gray-100">
        <tr>
            <th class="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Title</th>
            <th class="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
            <th class="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Body Part</th>
            <th class="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Level</th>
        </tr>
    </thead>
    <tbody class="divide-y divide-gray-200">
        {% for exercise in exercises %}
            <tr class="hover:bg-gray-50 transition duration-200 cursor-pointer"
                hx-get="{{ url_for('base.show_exercise', exercise_id=exercise.id) }}"
                hx-trigger="click"
                hx-target="#modal-exercise-content"   
            >
                <td class="p-3 text-sm text-gray-700">{{ exercise.title }}</td>
                <td class="p-3 text-sm text-gray-700">{{ exercise.type }}</td>
                <td class="p-3 text-sm text-gray-700">{{ exercise.body_part }}</td>
                <td class="p-3 text-sm text-gray-700">{{ exercise.level }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<dialog id="modal-exercise-content" class="w-full md:w-2/3 mx-auto focus-visible:outline-none">

</dialog>

<script>
    document.addEventListener('htmx:afterSwap', function (event) {
        if (event.target.id === 'modal-exercise-content') {
            const modal = document.getElementById('modal-exercise-content');
            modal.showModal();

            const closeButton = modal.querySelector('#modal-close-button');
            closeButton.addEventListener('click', function () {
                modal.close();
            });
        }
    });

    document.getElementById('modal-exercise-content').addEventListener('click', function (event) {
        const modal = event.target;
        if (modal.tagName === 'DIALOG' && event.target === modal) {
            modal.close();
        }
    });

    document.addEventListener('keydown', function (event) {
        if (event.key === 'Escape') {
            const modal = document.getElementById('modal-exercise-content');
            modal.close();
        }
    });
</script>

{% else %}

<p class="text-center text-gray-600"> No exercises for the given search </p>

{% endif %}

src/templates/partials/friend_search.html
<h1 class="text-center
    {% if message.error %}
        text-red-500
    {% else %}
        text-green-500
    {% endif %}
    ">
    {{message.message}}
</h1>

src/templates/partials/nutrition_table.html
{% if food %}
<table class="w-full max-w-4xl mx-auto border-collapse bg-white shadow-md rounded-lg overflow-hidden">
    <thead class="bg-gray-100">
        <tr>
            <th class="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Food</th>
            <th class="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Calories</th>
            <th class="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Protein</th>
            <th class="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Carbohydrates</th>
            <th class="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Fats</th>
        </tr>
    </thead>
    <tbody class="divide-y divide-gray-200">
        {% for f in food %}
            <tr class="hover:bg-gray-50 transition duration-200 cursor-pointer"
            >
                <td class="p-3 text-sm text-gray-700">{{ f.name|title }}</td>
                <td class="p-3 text-sm text-gray-700">{{ f.calories }}</td>
                <td class="p-3 text-sm text-gray-700">{{ f.proteins }}</td>
                <td class="p-3 text-sm text-gray-700">{{ f.carbs }}</td>
                <td class="p-3 text-sm text-gray-700">{{ f.fats }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% else %}

<p class="text-center text-gray-600"> No food for the given search </p>

{% endif %}

src/templates/partials/show_exercise.html
<div class="w-full mx-auto bg-white shadow-lg rounded-lg overflow-hidden">
    <div class="px-6 py-8">
        <div class="flex flex-col md:flex-row items-start space-y-4 md:space-y-0 md:space-x-6">
            <div class="w-full md:w-2/3">
                <div class="flex flex-row justify-between items-center">
                    <h1 class="text-3xl font-bold mb-4 bg-gradient-to-r from-violet-600 to-indigo-600 bg-clip-text text-transparent">
                        {{ exercise.title }}
                    </h1>
                    <div id="modal-close-button" class="cursor-pointer">
                        <svg height="30px" width="30px" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 26 26" xml:space="preserve" fill="#EF5350" stroke="#EF5350"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <g> <path style="fill:#EF5350;" d="M21.125,0H4.875C2.182,0,0,2.182,0,4.875v16.25C0,23.818,2.182,26,4.875,26h16.25 C23.818,26,26,23.818,26,21.125V4.875C26,2.182,23.818,0,21.125,0z M18.78,17.394l-1.388,1.387c-0.254,0.255-0.67,0.255-0.924,0 L13,15.313L9.533,18.78c-0.255,0.255-0.67,0.255-0.925-0.002L7.22,17.394c-0.253-0.256-0.253-0.669,0-0.926l3.468-3.467 L7.221,9.534c-0.254-0.256-0.254-0.672,0-0.925l1.388-1.388c0.255-0.257,0.671-0.257,0.925,0L13,10.689l3.468-3.468 c0.255-0.257,0.671-0.257,0.924,0l1.388,1.386c0.254,0.255,0.254,0.671,0.001,0.927l-3.468,3.467l3.468,3.467 C19.033,16.725,19.033,17.138,18.78,17.394z"></path> </g> </g></svg>
                    </div>
                </div>
                <div class="grid grid-cols-2 gap-4 mb-6">
                    <div class="bg-violet-50 p-3 rounded-lg">
                        <p class="text-xs font-semibold text-gray-500 mb-1">Type</p>
                        <p class="text-sm font-medium text-gray-800">{{ exercise.type }}</p>
                    </div>
                    <div class="bg-violet-50 p-3 rounded-lg">
                        <p class="text-xs font-semibold text-gray-500 mb-1">Body Part</p>
                        <p class="text-sm font-medium text-gray-800">{{ exercise.body_part }}</p>
                    </div>
                    <div class="bg-violet-50 p-3 rounded-lg">
                        <p class="text-xs font-semibold text-gray-500 mb-1">Level</p>
                        <p class="text-sm font-medium text-gray-800">{{ exercise.level }}</p>
                    </div>
                    <div class="bg-violet-50 p-3 rounded-lg">
                        <p class="text-xs font-semibold text-gray-500 mb-1">Equipment</p>
                        <p class="text-sm font-medium text-gray-800">
                            {{ exercise.equipment or 'No Equipment Required' }}
                        </p>
                    </div>
                </div>

                <div class="mb-6">
                    <h2 class="text-xl font-semibold mb-3 text-gray-800">Description</h2>
                    <p class="text-gray-600 leading-relaxed">
                        {{ exercise.description }}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

src/templates/partials/training_class_promotion.html
{% for training_class in training_classes %}
    {% include "components/training_class_promotion.html" %}
{% endfor %}

src/templates/partials/training_class_table.html
{% for training_class in training_classes %}
    {% include "components/training_class.html" %}
{% endfor %}

src/templates/partials/workout-requests-table.html
{% if clients_request %}
    <table  class="w-full max-w-4xl mx-auto border-collapse bg-white shadow-md rounded-lg overflow-hidden">
        <thead class="bg-gray-100">
            <tr>
                <th class="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Client</th>
                <th class="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Timestamp</th>
                <th class="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Description</th>
                <th class="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                <th class="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Accept</th>
                <th class="p-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Reject</th>
            </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
            {% for request in clients_request %}
                {% set client = request.get_client() %}
                <tr>
                    <td class="p-3 text-sm text-gray-700">{{ client.first_name|title }} {{ client.last_name|title }}</td>
                    <td class="p-3 text-sm text-gray-700">{{ request.timestamp.strftime('%Y-%m-%d %H:%M') }}</td>
                    <td class="p-3 text-sm text-gray-700">{{ request.description }}</td>
                    <td class="p-3 text-sm text-gray-700">{{ request.status}}</td>
                    <td class="p-3 text-sm text-gray-700">
                        <button 
                            class="text-violet-600 hover:text-violet-700" 
                            hx-post="{{ url_for('trainer.accept_plan_request', workout_request_id=request.id, client_id = client.id )}}" 
                            hx-target="#workout-requests-table"
                            hx-swap="innerHTML"
                            hx-include="#title, #description, #exercise-dropdown"
                        >
                            Accept
                        </button>
                    </td>
                    <td class="p-3 text-sm text-gray-700">
                        <button 
                            class="text-violet-600 hover:text-violet-700" 
                            hx-post="{{ url_for('trainer.reject_plan_request', workout_request_id = request.id)}}" 
                            hx-target="#workout-requests-table"
                            hx-swap="innerHTML"
                        >
                            Reject  
                        </button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p class="text-center text-gray-600"> No Pending requests</p>
    {% endif %}

{% if message %}
<h1 class="text-center text-red-500 mt-10">
    {{message}}
</h1>
{% endif %}

src/templates/partials/workout_plan_active_button.html
<button 
    hx-post="{{ url_for('client.toggle_workout_plan_active', plan_id=workout_plan.id) }}"
    hx-swap="outerHTML"
    class="px-3 py-1 rounded-full text-sm font-semibold {% if workout_plan.is_active %}bg-green-100 text-green-800{% else %}bg-gray-100 text-gray-800{% endif %}">
    {{ 'Active' if workout_plan.is_active else 'Inactive' }}
</button>

src/templates/partials/workout_plan_request.html
<h1 class="text-center
    {% if message.error %}
        text-red-500
    {% else %}
        text-green-500
    {% endif %}
    ">
    {{message.message}}
</h1>

{% if htmx %}
<div hx-swap-oob="true" id="previous-workout-requests">
    {% include "components/previous_workout_requests.html" %}
</div>
{% endif %}